#!/bin/zsh
# change keyboard brightness
# usage: kb-backlight x
#   where x is an integer to increase by (usually 1 or -1)

LOCATION='/sys/devices/platform/asus-nb-wmi/leds/asus::kbd_backlight/brightness'
SAVE="$HOME/bin/.kb-backlight"

if [ -f $SAVE ]; then
    CURRENT=$(<$SAVE)
else
    CURRENT=0
fi

((VAL = CURRENT + $1))

if [ "$VAL" -ge 0 ] && [ "$VAL" -le 3 ]; then
    echo $VAL > $LOCATION
    echo $VAL > $SAVE
fi
